name: Build and Deploy to Vercel

on:
  push:
    branches:
      - develop 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-app-image .

      # Log in to Vercel CLI
      - name: Log in to Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      # Deploy to Vercel
      - name: Deploy to Vercel
        run: |
          vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      # Clean up
      - name: Clean up
        run: docker system prune -af
